// consultorio-psicologico/src/components/AgregarPaciente.vue
<template>
  <div>
    <h2>Agregar Paciente</h2>
    <form @submit.prevent="submitForm">
      <div>
        <label for="tipo_documento">Tipo de Documento:</label>
        <input v-model="paciente.tipo_documento" id="tipo_documento" required />
      </div>
      <div>
        <label for="numero_documento">Número de Documento:</label>
        <input v-model.number="paciente.numero_documento" id="numero_documento" type="number" required />
      </div>
      <div>
        <label for="nombre">Nombre:</label>
        <input v-model="paciente.nombre" id="nombre" required />
      </div>
      <div>
        <label for="genero">Género:</label>
        <input v-model="paciente.genero" id="genero" required />
      </div>
      <div>
        <label for="estrato">Estrato:</label>
        <input v-model="paciente.estrato" id="estrato" required />
      </div>
      <div>
        <label for="barrio">Barrio:</label>
        <input v-model="paciente.barrio" id="barrio" required />
      </div>
      <div>
        <label for="localidad">Localidad:</label>
        <input v-model="paciente.localidad" id="localidad" required />
      </div>
      <div>
        <label for="escolaridad">Escolaridad:</label>
        <input v-model="paciente.escolaridad" id="escolaridad" required />
      </div>
      <div>
        <label>Seleccione quién estará a cargo:</label>
        <select v-model="encargado">
          <option value="practicante">Practicante</option>
          <option value="profesional">Profesional</option>
        </select>
      </div>
      <div v-if="encargado === 'practicante'">
        <label for="numero_documento_practicante">ID Practicante:</label>
        <input v-model.number="paciente.numero_documento_practicante" id="numero_documento_practicante" type="number" />
      </div>
      <div v-if="encargado === 'profesional'">
        <label for="numero_documento_profesional">ID Profesional:</label>
        <input v-model.number="paciente.numero_documento_profesional" id="numero_documento_profesional" type="number" />
      </div>
      <button type="submit">Agregar Paciente</button>
    </form>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue';
import { Paciente } from '../types';
import { createPaciente } from '../services/api';

export default defineComponent({
  name: 'AgregarPaciente',
  setup() {
    const paciente = ref<Paciente>({
      numero_documento: 0,
      tipo_documento: '',
      nombre: '',
      genero: '',
      estrato: '',
      barrio: '',
      localidad: '',
      escolaridad: '',
    });
    const encargado = ref('');

    const submitForm = async () => {
      try {
        await createPaciente(paciente.value);
        alert('Paciente agregado exitosamente');
        // Reset form
        paciente.value = {
          numero_documento: 0,
          tipo_documento: '',
          nombre: '',
          genero: '',
          estrato: '',
          barrio: '',
          localidad: '',
          escolaridad: '',
        };
        encargado.value = '';
      } catch (error) {
        console.error('Error al agregar paciente:', error);
        alert('Error al agregar paciente');
      }
    };

    return {
      paciente,
      encargado,
      submitForm,
    };
  },
});
</script>

// frontend/src/components/AgregarPaciente.jsx
import { useState } from 'react';

function AgregarPacientes() {
  // Estado para los valores del formulario
  const [formData, setFormData] = useState({
    tipo_documento: '',
    numero_documento: '',
    nombre: '',
    genero: '',
    estrato: '',
    barrio: '',
    localidad: '',
    escolaridad: '',
    seleccion: 'practicante', // Valor inicial para la selección entre practicante y profesional
    id_practicante_fk: '',
    id_profesional_fk: ''
  });

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData({
      ...formData,
      [name]: value,
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    
    // Validar que solo uno de los campos (practicante o profesional) esté lleno
    if ((formData.seleccion === 'practicante' && !formData.id_practicante_fk) || 
        (formData.seleccion === 'profesional' && !formData.id_profesional_fk)) {
      alert('Por favor, complete el ID seleccionado antes de enviar.');
      return;
    }
    
    // Reiniciar el formulario después de enviar
    setFormData({
      tipo_documento: '',
      numero_documento: '',
      nombre: '',
      genero: '',
      estrato: '',
      barrio: '',
      localidad: '',
      escolaridad: '',
      seleccion: 'practicante',
      id_practicante_fk: '',
      id_profesional_fk: ''
    });
    
    alert('¡Registro exitoso!');
  };

  return (
    <form onSubmit={handleSubmit} style={{ maxWidth: '400px', margin: '0 auto' }}>
      <h2>Registro de Paciente</h2>
      
      {/* Campos del formulario */}
      <div style={{ marginBottom: '10px' }}>
        <label htmlFor="tipo_documento">Tipo de Documento:</label>
        <select
          id="tipo_documento"
          name="tipo_documento"
          value={formData.tipo_documento}
          onChange={handleChange}
          required
          style={{ width: '100%', padding: '8px', marginTop: '5px' }}
        >
          <option value="">Seleccione...</option>
          <option value="CC">Cédula de Ciudadanía (CC)</option>
          <option value="TI">Tarjeta de Identidad (TI)</option>
          <option value="CE">Cédula de Extranjería (CE)</option>
        </select>
      </div>

      
      <div style={{ marginBottom: '10px' }}>
        <label htmlFor="numero_documento">Número de Documento:</label>
        <input
          type="number"
          id="numero_documento"
          name="numero_documento"
          value={formData.numero_documento}
          onChange={handleChange}
          required
          style={{ width: '100%', padding: '8px', marginTop: '5px' }}
        />
      </div>
      
      <div style={{ marginBottom: '10px' }}>
        <label htmlFor="nombre">Nombre:</label>
        <input
          type="text"
          id="nombre"
          name="nombre"
          value={formData.nombre}
          onChange={handleChange}
          required
          style={{ width: '100%', padding: '8px', marginTop: '5px' }}
        />
      </div>
      
      <div style={{ marginBottom: '10px' }}>
        <label htmlFor="genero">Género:</label>
        <select
          id="genero"
          name="genero"
          value={formData.genero}
          onChange={handleChange}
          required
          style={{ width: '100%', padding: '8px', marginTop: '5px' }}
        >
          <option value="">Seleccione...</option>
          <option value="Masculino">Masculino</option>
          <option value="Femenino">Femenino</option>
          <option value="Otro">Otro</option>
        </select>
      </div>
      
      <div style={{ marginBottom: '10px' }}>
        <label htmlFor="estrato">Estrato:</label>
        <input
          type="number"
          id="estrato"
          name="estrato"
          value={formData.estrato}
          onChange={handleChange}
          required
          style={{ width: '100%', padding: '8px', marginTop: '5px' }}
        />
      </div>
      
      <div style={{ marginBottom: '10px' }}>
        <label htmlFor="barrio">Barrio:</label>
        <input
          type="text"
          id="barrio"
          name="barrio"
          value={formData.barrio}
          onChange={handleChange}
          required
          style={{ width: '100%', padding: '8px', marginTop: '5px' }}
        />
      </div>
      
      <div style={{ marginBottom: '10px' }}>
        <label htmlFor="localidad">Localidad:</label>
        <input
          type="text"
          id="localidad"
          name="localidad"
          value={formData.localidad}
          onChange={handleChange}
          required
          style={{ width: '100%', padding: '8px', marginTop: '5px' }}
        />
      </div>
      
      <div style={{ marginBottom: '10px' }}>
        <label htmlFor="escolaridad">Escolaridad:</label>
        <input
          type="text"
          id="escolaridad"
          name="escolaridad"
          value={formData.escolaridad}
          onChange={handleChange}
          required
          style={{ width: '100%', padding: '8px', marginTop: '5px' }}
        />
      </div>
      
      <div style={{ marginBottom: '10px' }}>
        <label htmlFor="seleccion">Seleccione quién estará a cargo:</label>
        <select
          id="seleccion"
          name="seleccion"
          value={formData.seleccion}
          onChange={handleChange}
          required
          style={{ width: '100%', padding: '8px', marginTop: '5px' }}
        >
          <option value="practicante">Practicante</option>
          <option value="profesional">Profesional</option>
        </select>
      </div>
      
      {formData.seleccion === 'practicante' && (
        <div style={{ marginBottom: '10px' }}>
          <label htmlFor="id_practicante_fk">ID Practicante:</label>
          <input
            type="number"
            id="id_practicante_fk"
            name="id_practicante_fk"
            value={formData.id_practicante_fk}
            onChange={handleChange}
            required={formData.seleccion === 'practicante'}
            style={{ width: '100%', padding: '8px', marginTop: '5px' }}
          />
        </div>
      )}
      
      {formData.seleccion === 'profesional' && (
        <div style={{ marginBottom: '10px' }}>
          <label htmlFor="id_profesional_fk">ID Profesional:</label>
          <input
            type="number"
            id="id_profesional_fk"
            name="id_profesional_fk"
            value={formData.id_profesional_fk}
            onChange={handleChange}
            required={formData.seleccion === 'profesional'}
            style={{ width: '100%', padding: '8px', marginTop: '5px' }}
          />
        </div>
      )}
      
      <button type="submit" style={{ padding: '10px 20px', backgroundColor: '#4CAF50', color: '#fff', border: 'none', cursor: 'pointer' }}>
        Registrarse
      </button>
    </form>
  );
}

export default AgregarPacientes;
